[package]
name = "wallet_canister"
version = "0.1.0"

[dependencies]
encoding.mo = "github.com/aviate-labs/encoding.mo"
base = "0.13.0"
vector = "0.4.1"
candy = "0.3.0"
map = "9.0.1"
encoding = "https://github.com/aviate-labs/encoding.mo#v0.4.1"
serde = "3.2.1"
sha3 = "0.1.1"
sha2 = "0.1.0"
tecdsa = "0.0.4"
stableheapbtreemap = "1.5.0"
icrc7-mo = "0.5.0"
icrc3-mo = "0.2.6"
icrc37-mo = "0.5.1"
star = "0.1.1"
libsecp256k1 = "0.1.0"
rlprelaxed = "https://github.com/relaxed04/rlp-motoko#main"
evm-txs = "https://github.com/av1ctor/evm-txs.mo#main"
class-plus = "0.0.1"
timer-tool = "0.1.0"
